# Generated by Django 5.2.4 on 2025-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
        migrations.AddField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
