# Generated by Django 5.2.4 on 2025-09-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0002_remove_poll_is_active_poll_expiry_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_vote',
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='option',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'user')},
        ),
    ]
